spring:
  application:
    name: heroes_passthrough
    
server:
  port: 8085
  servlet:
    session:
      cookie:
        domain: .localhost:4200
        http-only: true
        path: /
        
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/